#!/usr/bin/env bash
# A Bash script that pings an IP address passed as an argument.
# Requirements
# Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
# If no argument passed
# Ping the IP 5 times

if [ $# -eq 0 ]; then
        echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
        exit
elseif [ $# -gt 1 ]; then
          echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
          exit
else
          ping "$1" -c 5
fi
