#!/usr/bin/env bash
# A script that display list of currently running processes
# A script that show all processes, for all users, including those which might not have a TTY
# A script that display in a user-oriented format
# A script that show process hierarchy

ps -a -x -u -f
